### ISSUE TITLE
S02.02-Exercise-Menus Improper Parsing of JSON

### ISSUE THREAD

**Issue by FlailingElbows** [udacity/ud851-Sunshine#69]
On line 60 of OpenWeatherJsonUtils.java the OWM_DESCRIPTION variable value is improperly set to "forecast".  When the JSON is parsed, it has no "forecast" element, and throws an exception, causing the weather results to be empty.  The result is a blank weather screen.  The correct value should probably be "description" as that matches an element from the JSON, causes the parsing to succeed, and appears to be what was intended to be used.

**Comment by FlailingElbows** [comment]
Or perhaps OWM_DESCRIPTION supposed to have the value "main" since that is what the previous exercise (S02.01-Exercise-Networking) was using.  I tried this value and it worked as well, and actually gives the same output as if "description" is used.

**Comment by FlailingElbows** [comment]
Just looked at S02.02-Solution-Menus project and indeed in there it uses OWM_DESCRIPTION = "main", so I guess that's definitely what should be used in the exercise.

**Comment by marshallaf** [comment]
I had this problem too - but the cause isn't actually the source, since it is correct in the GitHub repo.
What happened to me was that I initially named the menu file "main.xml" since that's what we called it in the GitHub search toy app, but then renamed it "forecast.xml" when I realized that would match the TODO instruction. During this refactor, Android Studio mistakenly changes the code from `OWM_DESCRIPTION = "main";` to `OWM_DESCRIPTION = "forecast";`.
