### ISSUE TITLE
Importing Sunshine to android studio

### ISSUE THREAD

**Issue by HeirPrince** [udacity/ud851-Sunshine#70]
Hey guys can anyone help on how to import these projects in android studio

**Comment by vr5411** [comment]
Hi,
Maybe something is screwed up with your local clone / copy of the repo?!
You should probably start fresh w/ deleting your local project and repeating cloning the repo / downloading the ZIP.
Then, run your android studio as an Administrator.
To open pre-existing Android code, select the Import Project option from the Android Studio dialog. You can close your currently open project to get back to the Android Studio starting menu.
Go to dir (example from my machine):
f:\Dev\GitHub\ud851-Exercises\Lesson01-Favorite-Toys\T01.01-Exercise-CreateLayout\
and import it.
Since, Studio is running under administrative privileges, accept any inputs to download missing components.
Run your first app before changing anything to verify it is working fine. As it should. I just run it.
Use TODO to guide you with your tasks.
Good luck.
Kind Regards, Veselin

**Comment by simranjain1507** [comment]
should i import folder by folder, or whole project together.?

**Comment by vr5411** [comment]
Hi,
Each "folder" at level as in my previous post is already a project by itself.
And it is planned to import them one by one as instructed by training tutorials.
If you try at level of ud851-Exercises you'll get questions how to import and neither way is the desired one.
Br, Veselin

**Comment by simranjain1507** [comment]
thank you.. @vr5411 
it is working fine now. thank you.

**Comment by simranjain1507** [comment]
while importing, there are 2 options, which one to select?
create project from existing sources 
or
import project from external model
??
